import Head from 'next/head'
import { Inter } from '@next/font/google'
import Hero from 'components/Hero'
import Navbar from 'components/Navbar'
import { MainnetLaunch } from 'components/MainnetLaunch'
import { Features } from 'components/Features'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>MyXDC wallet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <MainnetLaunch />
      <Features />
    </>
  )
}
